### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by anandheritage** [cppforlife/bosh-warden-cpi-release#1]
Director task 4
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages > apache2/4fdebebaa6fcc528155afc5fabae6486131c0cee. Failed: Creating VM with agent ID '0e4a11ab-51ab-4e01-9b81-9691a7a102f8': Creating container: bad response: invalid character 'i' looking for beginning of value (00:00:01)

Error 100: Creating VM with agent ID '0e4a11ab-51ab-4e01-9b81-9691a7a102f8': Creating container: bad response: invalid character 'i' looking for beginning of value

**Comment by dpb587-pivotal** [comment]
We ran into this as well when using bosh-lite, and updating to a newer box of bosh-lite helped. If you're using bosh-lite, maybe try a `git pull` and recreate the VM.
