### ISSUE TITLE
Deploying CF to BOSH-lite on GCP

### ISSUE THREAD

**Issue by dgodd** [cppforlife/bosh-warden-cpi-release#3]
We have been using bosh-lite to to deploy CF on GCP. The deployment has been working well, however when running CATs on the deployed instances, we have been seeing extreme inconsistencies, most runs have approximately 8 failures, with minimal consistency as to which tests fail. 

We have been deploying on GCP using a `n1-standard-16` (16 vCPU and 60Gb RAM). We have tried tweaking the machine to use local SSDs for each of `/var/vcap/store` and `/var/vcap/data` since it appeared to be an IOPS issue, however that has not noticeably altered the success rate.

We have been running CATs using this CPI on AWS (using garden-linux) quite successfully, in attempting to shift to GCP we have used both garden-linux and garden-runc, but both have given similar results.

The most apparent failures are `502 Bad Gateway: Registered endpoint failed to handle the request`, which makes us suspect something to do with container networking.

Is there an expectation that bosh-warden-cpi-release would work well with GCP?

**Comment by cppforlife** [comment]
@dgodd bosh-warden-cpi-release does not know or care where it's running. it's all about the workload running in garden containers and how they are using available system resources. currently this cpi does not limit container impact in any way (ie no way to specify that container should consume max memory blah or max io). i would recommend looking at specific cf components and potential errors they are raising (and where) to identify the instability. n1-standard-16 is more than enough.
